-- MySQL Script generated by MySQL Workbench
-- Fri Jan 20 04:44:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbmangerlocal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbmangerlocal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbmangerlocal` DEFAULT CHARACTER SET utf8 ;
USE `dbmangerlocal` ;

-- -----------------------------------------------------
-- Table `dbmangerlocal`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmangerlocal`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postalcode` INT(5) NOT NULL,
  `phonenumber` INT(10) NOT NULL,
  `birthdate` DATE NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmangerlocal`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmangerlocal`.`shop` (
  `idShop` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NOT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idShop`, `user_idUser`),
  INDEX `fk_shop_user1_idx` (`user_idUser` ASC),
  CONSTRAINT `fk_shop_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `dbmangerlocal`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmangerlocal`.`shopAdress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmangerlocal`.`shopAdress` (
  `idShopAdress` INT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postalCode` INT(5) NOT NULL,
  `shop_idShop` INT NOT NULL,
  `shop_user_idUser` INT NOT NULL,
  PRIMARY KEY (`idShopAdress`, `shop_idShop`, `shop_user_idUser`),
  INDEX `fk_shopAdress_shop1_idx` (`shop_idShop` ASC, `shop_user_idUser` ASC),
  CONSTRAINT `fk_shopAdress_shop1`
    FOREIGN KEY (`shop_idShop` , `shop_user_idUser`)
    REFERENCES `dbmangerlocal`.`shop` (`idShop` , `user_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmangerlocal`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmangerlocal`.`product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmangerlocal`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmangerlocal`.`category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmangerlocal`.`product_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmangerlocal`.`product_has_category` (
  `product_idProduct` INT NOT NULL,
  `category_idCategory` INT NOT NULL,
  PRIMARY KEY (`product_idProduct`, `category_idCategory`),
  INDEX `fk_product_has_category_category1_idx` (`category_idCategory` ASC),
  INDEX `fk_product_has_category_product1_idx` (`product_idProduct` ASC),
  CONSTRAINT `fk_product_has_category_product1`
    FOREIGN KEY (`product_idProduct`)
    REFERENCES `dbmangerlocal`.`product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_category_category1`
    FOREIGN KEY (`category_idCategory`)
    REFERENCES `dbmangerlocal`.`category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmangerlocal`.`shop_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmangerlocal`.`shop_has_product` (
  `shop_idShop` INT NOT NULL,
  `shop_user_idUser` INT NOT NULL,
  `product_idProduct` INT NOT NULL,
  PRIMARY KEY (`shop_idShop`, `shop_user_idUser`, `product_idProduct`),
  INDEX `fk_shop_has_product_product1_idx` (`product_idProduct` ASC),
  INDEX `fk_shop_has_product_shop1_idx` (`shop_idShop` ASC, `shop_user_idUser` ASC),
  CONSTRAINT `fk_shop_has_product_shop1`
    FOREIGN KEY (`shop_idShop` , `shop_user_idUser`)
    REFERENCES `dbmangerlocal`.`shop` (`idShop` , `user_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_has_product_product1`
    FOREIGN KEY (`product_idProduct`)
    REFERENCES `dbmangerlocal`.`product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
