-- MySQL Script generated by MySQL Workbench
-- Wed Jan 18 10:23:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shop` (
  `idShop` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `position_idPosition` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idShop`, `position_idPosition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `firstname` VARCHAR(30) NOT NULL,
  `lastname` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `birthdate` DATE NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postalcode` INT(5) NOT NULL,
  `phonenumber` INT(10) NOT NULL,
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Shop_idShop` INT NOT NULL,
  `Shop_position_idPosition` INT NOT NULL,
  PRIMARY KEY (`idUser`, `Shop_idShop`, `Shop_position_idPosition`),
  INDEX `fk_user_Shop1_idx` (`Shop_idShop` ASC, `Shop_position_idPosition` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phonenumber_UNIQUE` (`phonenumber` ASC) VISIBLE,
  CONSTRAINT `fk_user_Shop1`
    FOREIGN KEY (`Shop_idShop` , `Shop_position_idPosition`)
    REFERENCES `mydb`.`Shop` (`idShop` , `position_idPosition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`shopadress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shopadress` (
  `idShopadress` INT NOT NULL,
  `adress` VARCHAR(255) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `Postalcode` INT NOT NULL,
  `Shop_idShop` INT NOT NULL,
  `Shop_position_idPosition` INT NOT NULL,
  PRIMARY KEY (`idShopadress`, `Shop_idShop`, `Shop_position_idPosition`),
  INDEX `fk_Shopadress_Shop1_idx` (`Shop_idShop` ASC, `Shop_position_idPosition` ASC) VISIBLE,
  CONSTRAINT `fk_Shopadress_Shop1`
    FOREIGN KEY (`Shop_idShop` , `Shop_position_idPosition`)
    REFERENCES `mydb`.`Shop` (`idShop` , `position_idPosition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `idProducts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shop_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shop_has_products` (
  `Shop_idShop` INT NOT NULL,
  `Shop_position_idPosition` INT NOT NULL,
  `products_idProducts` INT NOT NULL,
  PRIMARY KEY (`Shop_idShop`, `Shop_position_idPosition`, `products_idProducts`),
  INDEX `fk_Shop_has_products_products1_idx` (`products_idProducts` ASC) VISIBLE,
  INDEX `fk_Shop_has_products_Shop1_idx` (`Shop_idShop` ASC, `Shop_position_idPosition` ASC) VISIBLE,
  CONSTRAINT `fk_Shop_has_products_Shop1`
    FOREIGN KEY (`Shop_idShop` , `Shop_position_idPosition`)
    REFERENCES `mydb`.`Shop` (`idShop` , `position_idPosition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shop_has_products_products1`
    FOREIGN KEY (`products_idProducts`)
    REFERENCES `mydb`.`products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `idCategory` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products_has_category` (
  `products_idProducts` INT NOT NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`products_idProducts`, `category_idcategory`),
  INDEX `fk_products_has_category_category1_idx` (`category_idcategory` ASC) VISIBLE,
  INDEX `fk_products_has_category_products1_idx` (`products_idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_category_products1`
    FOREIGN KEY (`products_idProducts`)
    REFERENCES `mydb`.`products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_category_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `mydb`.`category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
